version: "2.0"

dependencies: https://raw.githubusercontent.com/Ginxo/rhba/${BRANCH}/.ci/project-dependencies.yaml?token=${GITHUB_TOKEN}

default:
  build-command:
    current: mvn clean install -Dproductized=true -Dmaven.test.failure.ignore=true -Dwebdriver.firefox.bin=/opt/tools/firefox-60esr/firefox-bin -Dmaven.wagon.httpconnectionManager.ttlSeconds=25 -Dmaven.wagon.http.retryHandler.count=3
    after:
      upstream: rm -rf ./*