name: Build Chain (Test)

on:
  issue_comment:
    types: [created]

jobs:
  build-chain:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Echo comment body
        if: ${{ !github.event.issue.pull_request }}
        run: echo ${{ github.event.comment.body }}
      - name: Echo comment pull_request
        if: ${{ github.event.issue.pull_request }}
        run: echo ${{ github.event.pull_request.id }}
